name: Build BULLETFEST
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  BuildGame:
    runs-on: ubuntu-latest
    outputs:
      gameVersion: ${{ steps.buildProject.outputs.buildVersion }}
    strategy:
      fail-fast: true
      matrix:
        targetPlatform:
          # - StandaloneOSX
          - StandaloneWindows64
          # - StandaloneLinux64
          # - Android
    steps:
      - name: Download required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full p7zip-rar

      - name: Copy game files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Download cache
        uses: actions/cache@v3
        with:
          path: |
            Library
            .utmp
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      - if: matrix.targetPlatform == 'Android'
        name: Free up space
        uses: kfir4444/free-disk-space@No_Fail

      - name: Build Project
        id: buildProject
        uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
          buildName: BULLETFEST
          versioning: None
          buildMethod: BuildScript.PerformBuild

      - if: matrix.targetPlatform != 'Android'
        name: Create archive
        run: |
          cd ./build/${{ matrix.targetPlatform }}
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -x'!BULLETFEST_B*' ../../BULLETFEST_${{ matrix.targetPlatform }}.7z *
          cd ../..

      - name: Upload build to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: ${{ matrix.targetPlatform == 'Android' && './build/Android/BULLETFEST.apk' || format('BULLETFEST_{0}.7z', matrix.targetPlatform) }}
          overwrite: true
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}

  NotifyDiscord:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    needs: BuildGame
    steps:
      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ needs.BuildGame.outputs.gameVersion }}
      #     release_name: BULLETFEST v${{ needs.BuildGame.outputs.gameVersion }}
      #     draft: false
      #     prerelease: false
      - uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'BULLETFEST'
        with:
          args: |
            ```A new build has been spotted!```
            `v${{ needs.BuildGame.outputs.gameVersion }}`
            Downloads:
            Windows: <https://drive.google.com/file/d/1XGsgIlPbgAfFbKJdavXmo9kvYYV1-TMS/view?usp=sharing>
            Linux: <https://drive.google.com/file/d/1rbJa1nVah6mPJ7R5nyyMFGKCw6hGE5jP/view?usp=sharing>
            MacOS (Intel 64 + Apple Silicon): <https://drive.google.com/file/d/1s8wX7TrDSbG93sG5IjDeVvACR_rwN3ET/view?usp=sharing>
            Android: <https://drive.google.com/file/d/1lp_WfbTHPEo4YUJvXchj0ghZbVPNIWNl/view?usp=sharing>
