name: CI
on:
  push:
    branches: ['main']

  workflow_dispatch:

env:
  UNITY_PATH: /opt/unity/editors/2023.1.8f1/Editor/Unity
jobs:
  Build:
    runs-on: ubuntu-latest
    container: unityci/hub:latest
    strategy:
      # If one jobs fail, they all do immediately
      fail-fast: true
      matrix:
        include:
          - targetPlatform: OSXUniversal
            outputFile: ./build/MacOS/BULLETFEST.app
            outputDir: ./build/MacOS/
            targetName: StandaloneOSX
            editorModule: mac-mono

          - targetPlatform: Win64
            outputFile: ./build/Windows/BULLETFEST.exe
            outputDir: ./build/Windows/
            targetName: StandaloneWindows64
            editorModule: windows-mono

          - targetPlatform: Linux64
            outputFile: ./build/Linux/BULLETFEST
            outputDir: ./build/Linux/
            targetName: StandaloneLinux64
            editorModule: linux-mono

          - targetPlatform: Android
            outputFile: ./build/Android/BULLETFEST.apk
            outputDir: ./build/Android/
            targetName: Android
            editorModule: android
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Download Packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install p7zip-full p7zip-rar dotnet

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Set Editor Install Location
        run: unity-hub ip -s /opt/unity/editors/

      - name: Install Editor for ${{ matrix.targetName }}
        run: unity-hub install --version 2023.1.8f1 --cm --m ${{ matrix.editorModule }}

      - name: Checkout Project
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            Library
            .utmp
          key: Library-${{ matrix.targetName }}
          restore-keys: |
            Library-

      - name: Build ${{ matrix.targetName }} Player
        run: $UNITY_PATH -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildTarget ${{ matrix.targetPlatform }} -executeMethod BuildScript.PerformBuild -serial ${{ secrets.UNITY_SERIAL }} -password ${{ secrets.UNITY_PASSWORD }} --username ${{ secrets.UNITY_EMAIL }}

      - name: Return License
        run: $UNITY_PATH -quit -batchmode -returnlicense -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }}

      - if: matrix.targetPlatform != 'Android'
        name: Create archive
        run: |
          cd ${{ matrix.outputDir }}
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -x'!BULLETFEST_B*' ../../BULLETFEST_${{ matrix.targetName }}.7z *
          cd ../..
      - if: matrix.targetPlatform != 'Android'
        name: Upload Standalone to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: 'BULLETFEST_${{ matrix.targetName }}.7z'
          overwrite: true
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}

      - if: matrix.targetPlatform == 'Android'
        name: Upload APK to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: './build/Android/BULLETFEST.apk'
          overwrite: true
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}

      - name: Get Build Version
        run: |
          touch projectVer.txt
          echo $(cat ./ProjectSettings/ProjectSettings.asset | grep bundleVersion | sed -n -e 's/^.*bundleVersion: //p' ) > projectVer.txt
      - uses: actions/upload-artifact@v3
        with:
          name: projectVer
          path: projectVer.txt
  NotifyDiscord:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: projectVer

      - name: Set Environment Variables
        run: |
          echo "ver=$(cat projectVer.txt)" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.ver }}
          release_name: BULLETFEST v${{ env.ver }}
          draft: false
          prerelease: false
      - uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'BULLETFEST'
        with:
          args: |
            ```A new build has been spotted!```

            `v${{ env.ver }}`

            Downloads:
            Windows: <https://drive.google.com/file/d/1XGsgIlPbgAfFbKJdavXmo9kvYYV1-TMS/view?usp=sharing>
            Linux: <https://drive.google.com/file/d/1rbJa1nVah6mPJ7R5nyyMFGKCw6hGE5jP/view?usp=sharing>
            MacOS (Intel 64 + Apple Silicon): <https://drive.google.com/file/d/1s8wX7TrDSbG93sG5IjDeVvACR_rwN3ET/view?usp=sharing>
            Android: <https://drive.google.com/file/d/1lp_WfbTHPEo4YUJvXchj0ghZbVPNIWNl/view?usp=sharing>
