#TESTING SCRIPT
# USED LOCALLY

name: CI
on:
  # push:
  #   branches: ['main']

  workflow_dispatch:

env:
  UNITY_PATH: /opt/unity/editors/2023.1.8f1/Editor/Unity
jobs:
  Build:
    runs-on: ubuntu-latest
    container: unityci/hub:latest
    strategy:
      # If one jobs fail, they all do immediately
      fail-fast: true
      matrix:
        include:
          - targetPlatform: buildOSXUniversalPlayer
            outputFile: ./build/MacOS/BULLETFEST.app
            outputDir: ./build/MacOS/
            targetName: StandaloneOSX
            editorModule: mac-mono

          - targetPlatform: buildWindows64Player
            outputFile: ./build/Windows/BULLETFEST.exe
            outputDir: ./build/Windows/
            targetName: StandaloneWindows64
            editorModule: windows-mono

          - targetPlatform: buildLinux64Player
            outputFile: ./build/Linux/BULLETFEST
            outputDir: ./build/Linux/
            targetName: StandaloneLinux64
            editorModule: linux-mono
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Download Packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install p7zip-full p7zip-rar

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set Editor Install Location
        run: unity-hub ip -s /opt/unity/editors/

      - name: Install Editor for ${{ matrix.targetName }}
        run: unity-hub install --version 2023.1.8f1 --cm --m ${{ matrix.editorModule }}

      - name: Build ${{ matrix.targetName }} Player
        run: $UNITY_PATH -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildTarget Win64 -executeMethod BuildScript.PerformBuild -serial ${{ secrets.UNITY_SERIAL }} -password ${{ secrets.UNITY_PASSWORD }} --username ${{ secrets.UNITY_EMAIL }}

      - name: Return License
        run: $UNITY_PATH -quit -batchmode -returnlicense -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }}
